AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'Gemfile*'
    - 'Rakefile'
    - 'bin/*'
    - 'config/**/*'

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Max: 120

Layout/HashAlignment:
  EnforcedHashRocketStyle: 'table'                                                               
  EnforcedColonStyle: 'table'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/HashTransformValues:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Lint/EnsureReturn:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false
