default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USERNAME', `whoami`.chomp) %>
  min_messages: ERROR

development:
  <<: *default
  database: <%= ENV.fetch('DEV_DB_NAME', 'crm_dev') %>

test: &test
  <<: *default
  encoding: utf8
  database: <%= ENV.fetch('TEST_DB_NAME', 'crm_test') %>
  load_seeds: true
  verbosity: silent
  migrate: false

production:
  url: <%= ENV.fetch('DATABASE_URL') if Rails.env.production? %>
